import type { WordItem } from '../types/crossword';

export const INITIAL_SAMPLE_WORDS: WordItem[] = [
  { id: '1', word: 'APPLE', japanese: 'りんご', sentence: 'An ____ a day keeps the doctor away.' },
  { id: '2', word: 'BANANA', japanese: 'バナナ', sentence: 'Monkeys love to eat a ____.' },
  { id: '3', word: 'CAT', japanese: '猫', sentence: 'The ____ sleeping on the sofa is cute.' },
  { id: '4', word: 'DOG', japanese: '犬', sentence: 'My ____ loves to play fetch in the park.' },
  { id: '5', word: 'ELEPHANT', japanese: '象', sentence: 'An ____ is the largest land animal.' },
  { id: '6', word: 'FLOWER', japanese: '花', sentence: 'Spring is when every ____ begins to bloom.' },
  { id: '7', word: 'GARDEN', japanese: '庭園', sentence: 'We grow fresh vegetables in our ____.' },
  { id: '8', word: 'HOUSE', japanese: '家・住宅', sentence: 'They built a modern ____ near the lake.' },
  { id: '9', word: 'ISLAND', japanese: '島', sentence: 'Hawaii is a famous tropical ____.' },
  { id: '10', word: 'JOURNEY', japanese: '旅・道のり', sentence: 'Life is a long and exciting ____.' },
  { id: '11', word: 'KITCHEN', japanese: 'キッチン・台所', sentence: 'Mom is cooking dinner in the ____.' },
  { id: '12', word: 'LIBRARY', japanese: '図書館', sentence: 'I borrowed three books from the school ____.' },
  { id: '13', word: 'MOUNTAIN', japanese: '山', sentence: 'Mount Fuji is the highest ____ in Japan.' },
  { id: '14', word: 'NOTEBOOK', japanese: 'ノート・帳面', sentence: 'Write down key ideas in your ____.' },
  { id: '15', word: 'OCEAN', japanese: '洋・大海原', sentence: 'Dolphins swim freely in the vast ____.' },
  { id: '16', word: 'PENCIL', japanese: '鉛筆', sentence: 'Please draw a sketch using a lead ____.' },
  { id: '17', word: 'QUEEN', japanese: '女王', sentence: 'The ____ wore a sparkling golden crown.' },
  { id: '18', word: 'RIVER', japanese: '川・河川', sentence: 'The Shinano is the longest ____ in Japan.' },
  { id: '19', word: 'SUNSHINE', japanese: '日光・ひざし', sentence: 'Bright ____ streamed through the window.' },
  { id: '20', word: 'TEACHER', japanese: '先生・教師', sentence: 'Our English ____ explained the grammar clearly.' },
];

export const PRESET_100_WORDS: WordItem[] = [
  ...INITIAL_SAMPLE_WORDS,
  { id: '21', word: 'UMBRELLA', japanese: '傘', sentence: 'Take an ____ with you because it might rain.' },
  { id: '22', word: 'VICTORY', japanese: '勝利', sentence: 'The team celebrated their big ____.' },
  { id: '23', word: 'WINDOW', japanese: '窓', sentence: 'Open the ____ to let fresh air in.' },
  { id: '24', word: 'YELLOW', japanese: '黄色', sentence: 'Sunflowers are bright ____ flowers.' },
  { id: '25', word: 'ZEBRA', japanese: 'シマウマ', sentence: 'A ____ has distinctive black and white stripes.' },
  { id: '26', word: 'AIRPORT', japanese: '空港', sentence: 'We arrived at the ____ two hours before flight.' },
  { id: '27', word: 'BRIDGE', japanese: '橋', sentence: 'The long ____ connects the two islands.' },
  { id: '28', word: 'CAMERA', japanese: 'カメラ', sentence: 'She took beautiful pictures with her new ____.' },
  { id: '29', word: 'DRAGON', japanese: '竜・ドラゴン', sentence: 'The mythical ____ breathed fire in the story.' },
  { id: '30', word: 'ENERGY', japanese: 'エネルギー・活力', sentence: 'Solar power is a clean source of ____.' },
  { id: '31', word: 'FOREST', japanese: '森林', sentence: 'Wild deer live deep inside the green ____.' },
  { id: '32', word: 'GUITAR', japanese: 'ギター', sentence: 'He plays the acoustic ____ very well.' },
  { id: '33', word: 'HOSPITAL', japanese: '病院', sentence: 'The doctor works at a city ____.' },
  { id: '34', word: 'INTERNET', japanese: 'インターネット', sentence: 'You can search for information on the ____.' },
  { id: '35', word: 'JACKET', japanese: 'ジャケット・上着', sentence: 'Put on a warm ____ as it is cold outside.' },
  { id: '36', word: 'KINGDOM', japanese: '王国', sentence: 'The brave knight protected the whole ____.' },
  { id: '37', word: 'LANTERN', japanese: 'ランタン・提灯', sentence: 'The paper ____ lit up the night street.' },
  { id: '38', word: 'MIRROR', japanese: '鏡', sentence: 'She looked at herself in the bathroom ____.' },
  { id: '39', word: 'NATURE', japanese: '自然', sentence: 'We went hiking to enjoy peaceful ____.' },
  { id: '40', word: 'ORANGE', japanese: 'オレンジ・橙色', sentence: 'An ____ is rich in vitamin C.' },
  { id: '41', word: 'PLANET', japanese: '惑星', sentence: 'Earth is the third ____ from the Sun.' },
  { id: '42', word: 'QUIET', japanese: '静かな', sentence: 'Please keep ____ in the reading room.' },
  { id: '43', word: 'RAINBOW', japanese: '虹', sentence: 'A colorful ____ appeared after the shower.' },
  { id: '44', word: 'SUMMER', japanese: '夏', sentence: 'Children love going to the beach in ____.' },
  { id: '45', word: 'TRAVEL', japanese: '旅行する', sentence: 'I hope to ____ around Europe next year.' },
  { id: '46', word: 'UNIVERSE', japanese: '宇宙', sentence: 'The expanding ____ holds billions of galaxies.' },
  { id: '47', word: 'VILLAGE', japanese: '村', sentence: 'My grandparents live in a quiet mountain ____.' },
  { id: '48', word: 'WINTER', japanese: '冬', sentence: 'Heavy snow falls in northern regions in ____.' },
  { id: '49', word: 'YOUTH', japanese: '青春・若さ', sentence: 'Enjoy your ____ while learning new things.' },
  { id: '50', word: 'ANIMAL', japanese: '動物', sentence: 'Lions and tigers are wild ____ species.' },
  { id: '51', word: 'BREAD', japanese: 'パン', sentence: 'Freshly baked ____ smells wonderful.' },
  { id: '52', word: 'CHEESE', japanese: 'チーズ', sentence: 'Pizza is delicious with melted ____ on top.' },
  { id: '53', word: 'DIAMOND', japanese: 'ダイヤモンド', sentence: 'A ____ is the hardest natural substance.' },
  { id: '54', word: 'EARTH', japanese: '地球', sentence: 'We must protect our home planet ____.' },
  { id: '55', word: 'FRIEND', japanese: '友達・友人', sentence: 'A true ____ supports you in hard times.' },
  { id: '56', word: 'GLASS', japanese: 'コップ・ガラス', sentence: 'He drank a cool ____ of water.' },
  { id: '57', word: 'HEART', japanese: '心臓・心', sentence: 'Listen to the steady beat of your ____.' },
  { id: '58', word: 'ICE', japanese: '氷', sentence: 'Add two cubes of ____ into the juice.' },
  { id: '59', word: 'JUICE', japanese: 'ジュース', sentence: 'Fresh orange ____ tastes sweet and sour.' },
  { id: '60', word: 'KEYBOARD', japanese: 'キーボード', sentence: 'Type your login password on the ____.' },
  { id: '61', word: 'LEMON', japanese: 'レモン', sentence: 'A ____ has a very sour flavor.' },
  { id: '62', word: 'MUSIC', japanese: '音楽', sentence: 'Listening to classical ____ helps me relax.' },
  { id: '63', word: 'NIGHT', japanese: '夜・夜間', sentence: 'Bright stars shine high in the dark ____.' },
  { id: '64', word: 'OFFICE', japanese: 'オフィス・事務所', sentence: 'She works at a downtown corporate ____.' },
  { id: '65', word: 'PEACE', japanese: '平和', sentence: 'Everyone wishes for global world ____.' },
  { id: '66', word: 'QUESTION', japanese: '質問・問題', sentence: 'If you have a ____, raise your hand.' },
  { id: '67', word: 'ROCKET', japanese: 'ロケット', sentence: 'The space ____ launched towards the Moon.' },
  { id: '68', word: 'SILVER', japanese: '銀・銀色', sentence: 'The shiny ____ ring sparkled in sunlight.' },
  { id: '69', word: 'TIGER', japanese: 'トラ', sentence: 'The striped ____ prowled through the jungle.' },
  { id: '70', word: 'VOICE', japanese: '声・音声', sentence: 'Her singing ____ sounded angelic and clear.' },
  { id: '71', word: 'WATER', japanese: '水', sentence: 'Drink plenty of fresh ____ every day.' },
  { id: '72', word: 'YOGURT', japanese: 'ヨーグルト', sentence: 'Eating ____ with fruit is healthy.' },
  { id: '73', word: 'AIR', japanese: '空気・大気', sentence: 'The mountain ____ feels crisp and pure.' },
  { id: '74', word: 'BIRD', japanese: '鳥', sentence: 'A little ____ sang sweetly on the branch.' },
  { id: '75', word: 'CLOUDS', japanese: '雲', sentence: 'White fluffly ____ floated across the blue sky.' },
  { id: '76', word: 'DREAM', japanese: '夢', sentence: 'Work hard to make your future ____ come true.' },
  { id: '77', word: 'EGG', japanese: '卵', sentence: 'He fried an ____ for breakfast.' },
  { id: '78', word: 'FAMILY', japanese: '家族', sentence: 'We gathered together for a happy ____ dinner.' },
  { id: '79', word: 'GREEN', japanese: '緑・緑色', sentence: 'Lush ____ grass covered the hillside.' },
  { id: '80', word: 'HONEY', japanese: 'ハチミツ', sentence: 'Bees make natural sweet ____.' },
  { id: '81', word: 'ISLANDS', japanese: '群島・島々', sentence: 'The archipelago consists of hundreds of small ____.' },
  { id: '82', word: 'JUNGLE', japanese: 'ジャングル・密林', sentence: 'Tropical animals thrive in the dense ____.' },
  { id: '83', word: 'KITE', japanese: '凧（たこ）', sentence: 'The windy weather was perfect for flying a ____.' },
  { id: '84', word: 'LIGHT', japanese: '光・明かり', sentence: 'Turn on the room ____ so we can read.' },
  { id: '85', word: 'MOON', japanese: '月', sentence: 'The full ____ illuminated the night sky.' },
  { id: '86', word: 'NEST', japanese: '鳥の巣', sentence: 'The mother bird built a twig ____.' },
  { id: '87', word: 'OWL', japanese: 'フクロウ', sentence: 'The wise nocturnal ____ hooted in the dark.' },
  { id: '88', word: 'PAPER', japanese: '紙', sentence: 'Fold the sheet of ____ into an origami crane.' },
  { id: '89', word: 'RING', japanese: '指輪・リング', sentence: 'He presented a beautiful gold ____.' },
  { id: '90', word: 'STARS', japanese: '星々', sentence: 'Thousands of twinkling ____ filled space.' },
  { id: '91', word: 'TREE', japanese: '木・樹木', sentence: 'The ancient oak ____ offered cool shade.' },
  { id: '92', word: 'UNDER', japanese: '〜の下に', sentence: 'The cat rested peacefully ____ the table.' },
  { id: '93', word: 'VALLEY', japanese: '谷・渓谷', sentence: 'A clear stream flows along the quiet ____.' },
  { id: '94', word: 'WIND', japanese: '風', sentence: 'A gentle sea ____ blew through her hair.' },
  { id: '95', word: 'XRAY', japanese: 'X線・レントゲン', sentence: 'The doctor checked the chest ____ scan.' },
  { id: '96', word: 'YEAR', japanese: '年・1年間', sentence: 'We wish you happiness in the new ____.' },
  { id: '97', word: 'ZOO', japanese: '動物園', sentence: 'Children love visiting pandas at the city ____.' },
  { id: '98', word: 'ACADEMY', japanese: '学園・アカデミー', sentence: 'She enrolled in the prestigious music ____.' },
  { id: '99', word: 'BALLOON', japanese: '風船', sentence: 'A red helium ____ drifted up into the sky.' },
  { id: '100', word: 'CREATIVITY', japanese: '創造性・創造力', sentence: 'Art classes help nurture student ____.' }
];
